name: 'PR CI check'

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
    title-check:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - uses: niehusst/shared-actions/pr-title-check@dist

    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run lint

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm test
